# export_weights.py — load archaos_model.pt and write ai_weights.h
# Run after train_archaos.py: python3 export_weights.py

import torch
import torch.nn as nn
import os

# ── Model definition (must match train_archaos.py) ──────────

class Encoder(nn.Module):
    def __init__(self, vocab, embed, hidden):
        super().__init__()
        self.emb = nn.Embedding(vocab, embed, padding_idx=0)
        self.gru = nn.GRU(embed, hidden, batch_first=True)
    def forward(self, x):
        return self.gru(self.emb(x))

class Decoder(nn.Module):
    def __init__(self, vocab, embed, hidden):
        super().__init__()
        self.emb = nn.Embedding(vocab, embed, padding_idx=0)
        self.gru = nn.GRU(embed, hidden, batch_first=True)
        self.fc  = nn.Linear(hidden, vocab)
    def forward(self, x, h):
        out, h = self.gru(self.emb(x), h)
        return self.fc(out), h

class Seq2Seq(nn.Module):
    def __init__(self, vocab, embed=128, hidden=512):
        super().__init__()
        self.encoder = Encoder(vocab, embed, hidden)
        self.decoder = Decoder(vocab, embed, hidden)
    def forward(self, src, tgt):
        _, h   = self.encoder(src)
        out, _ = self.decoder(tgt, h)
        return out

# ── Load checkpoint ──────────────────────────────────────────

print("Loading archaos_model.pt ...")
ckpt       = torch.load('archaos_model.pt', map_location='cpu')
ch2i       = ckpt['ch2i']
i2ch       = ckpt['i2ch']
vocab_size = ckpt['vocab_size']
EMBED      = ckpt['EMBED']
HIDDEN     = ckpt['HIDDEN']
MAX_IN     = ckpt['MAX_IN']
MAX_OUT    = ckpt['MAX_OUT']

model = Seq2Seq(vocab_size, EMBED, HIDDEN)
model.load_state_dict(ckpt['model_state'])
model.eval()
print(f"Loaded — vocab={vocab_size}  embed={EMBED}  hidden={HIDDEN}")

# ── Pure-Python tensor → C array (no numpy) ──────────────────

def fmt_array(name, tensor):
    flat = tensor.detach().cpu().reshape(-1).tolist()
    vals = ", ".join(f"{v:.6f}f" for v in flat)
    return f"static const float {name}[{len(flat)}] = {{\n    {vals}\n}};\n"

# ── Build header ─────────────────────────────────────────────

print("Exporting ai_weights.h ...")

lines = []
lines.append("// ai_weights.h — AUTO-GENERATED by export_weights.py")
lines.append("// Do not edit manually.\n")
lines.append("#ifndef AI_WEIGHTS_H")
lines.append("#define AI_WEIGHTS_H\n")

lines.append(f"#define AI_VOCAB_SIZE  {vocab_size}")
lines.append(f"#define AI_EMBED_SIZE  {EMBED}")
lines.append(f"#define AI_HIDDEN_SIZE {HIDDEN}")
lines.append(f"#define AI_MAX_IN      {MAX_IN}")
lines.append(f"#define AI_MAX_OUT     {MAX_OUT}")
lines.append("")

# Special token indices
lines.append(f"#define AI_PAD {ch2i['<PAD>']}")
lines.append(f"#define AI_SOS {ch2i['<SOS>']}")
lines.append(f"#define AI_EOS {ch2i['<EOS>']}")
lines.append(f"#define AI_UNK {ch2i['<UNK>']}")
lines.append("")

# char → index map (printable chars only)
printable = sorted([(c, idx) for c, idx in ch2i.items() if len(c) == 1], key=lambda x: x[1])
char_keys  = [ord(c) for c, _ in printable]
char_vals  = [idx    for _, idx in printable]

lines.append(f"#define AI_CHAR_MAP_SIZE {len(char_keys)}")
lines.append("static const unsigned char ai_char_keys[AI_CHAR_MAP_SIZE] = {")
lines.append("    " + ", ".join(str(v) for v in char_keys))
lines.append("};\n")
lines.append("static const int ai_char_vals[AI_CHAR_MAP_SIZE] = {")
lines.append("    " + ", ".join(str(v) for v in char_vals))
lines.append("};\n")

# index → char map
i2ch_arr = []
for i in range(vocab_size):
    c = i2ch.get(i, '\x00')
    if isinstance(c, str) and len(c) == 1 and c not in ('<PAD>','<SOS>','<EOS>','<UNK>'):
        i2ch_arr.append(ord(c))
    else:
        i2ch_arr.append(0)

lines.append("static const unsigned char ai_i2ch[AI_VOCAB_SIZE] = {")
lines.append("    " + ", ".join(str(v) for v in i2ch_arr))
lines.append("};\n")

# Encoder weights
enc = model.encoder
lines.append(fmt_array("ai_enc_emb_weight",    enc.emb.weight))
lines.append(fmt_array("ai_enc_gru_weight_ih", enc.gru.weight_ih_l0))
lines.append(fmt_array("ai_enc_gru_weight_hh", enc.gru.weight_hh_l0))
lines.append(fmt_array("ai_enc_gru_bias_ih",   enc.gru.bias_ih_l0))
lines.append(fmt_array("ai_enc_gru_bias_hh",   enc.gru.bias_hh_l0))

# Decoder weights
dec = model.decoder
lines.append(fmt_array("ai_dec_emb_weight",    dec.emb.weight))
lines.append(fmt_array("ai_dec_gru_weight_ih", dec.gru.weight_ih_l0))
lines.append(fmt_array("ai_dec_gru_weight_hh", dec.gru.weight_hh_l0))
lines.append(fmt_array("ai_dec_gru_bias_ih",   dec.gru.bias_ih_l0))
lines.append(fmt_array("ai_dec_gru_bias_hh",   dec.gru.bias_hh_l0))
lines.append(fmt_array("ai_dec_fc_weight",     dec.fc.weight))
lines.append(fmt_array("ai_dec_fc_bias",       dec.fc.bias))

lines.append("#endif // AI_WEIGHTS_H")

with open("ai_weights.h", "w") as f:
    f.write("\n".join(lines))

size = os.path.getsize("ai_weights.h")
print(f"Done! ai_weights.h written ({size/1024:.1f} KB)")
print("Copy it into your ArchaOS src/ directory.")
