build-x86_64-linux-gnu-x86_64-linux-gnu-release-lib-static/src_select_unit.o: \
 src/select/unit.c \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/stylesheet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/utils/utils.h \
 src/select/propget.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/computed.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h \
 src/select/computed.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/hint.h \
 src/select/autogenerated_computed.h src/select/autogenerated_propget.h \
 src/select/unit.h
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/stylesheet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h:
/home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/utils/utils.h:
src/select/propget.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/computed.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h:
src/select/computed.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/hint.h:
src/select/autogenerated_computed.h:
src/select/autogenerated_propget.h:
src/select/unit.h:
