build-x86_64-linux-gnu-x86_64-linux-gnu-release-lib-static/src_select_arena.o: \
 src/select/arena.c \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/arena.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/arena_hash.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/computed.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/computed.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/hint.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/autogenerated_computed.h
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/arena.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/arena_hash.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/computed.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/computed.h:
/home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/hint.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/autogenerated_computed.h:
