build-x86_64-linux-gnu-x86_64-linux-gnu-release-lib-static/src_parse_properties_autogenerated_align_self.o: \
 src/parse/properties/autogenerated_align_self.c \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/bytecode.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/opcodes.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/properties/properties.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/stylesheet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/stylesheet.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/bytecode.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/parse.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/vector.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/errors.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/functypes.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/types.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/mq.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/language.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/stack.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/lex/lex.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/input/inputstream.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/charset/utf8.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/buffer.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/parse.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/propstrings.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/utils/utils.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/hash.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/bloom.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/strings.h \
 /home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/properties/utils.h
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/bytecode.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/types.h:
/home/akushaji/ArchaOS/src/net/netsurf/libwapcaplet/include/libwapcaplet/libwapcaplet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/fpmath.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/properties.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/opcodes.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/properties/properties.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/stylesheet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/errors.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/functypes.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/stylesheet.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/bytecode/bytecode.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/parse.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/vector.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/errors.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/functypes.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/types.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/mq.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/language.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/stack.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/lex/lex.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/input/inputstream.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/charset/utf8.h:
/home/akushaji/ArchaOS/src/net/netsurf/libparserutils/include/parserutils/utils/buffer.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/parse.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/propstrings.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/utils/utils.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/hash.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/include/libcss/unit.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/bloom.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/select/strings.h:
/home/akushaji/ArchaOS/src/net/netsurf/libcss/src/parse/properties/utils.h:
