timeout: 3
interface_branding: ArchaOS v0.6 "Nexus" (Limine)

/ArchaOS v0.6 Nexus (Graphical Desktop / VESA)
    protocol: multiboot1
    kernel_path: boot():/boot/kernel.bin
    cmdline: gui

/ArchaOS v0.6 Nexus (Safe Mode - Text Shell)
    protocol: multiboot1
    kernel_path: boot():/boot/kernel.bin
    cmdline: text
