#!/usr/bin/env python3
"""
Scan program asset directories and generate src/user_assets.h and src/user_assets.asm
to embed program assets (such as DOOM.WAD) into the ArchaOS RAM VFS using fast NASM incbin.
"""

import sys
import os

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output_header.h> <assets_dir_or_file> [more_dirs...]")
        sys.exit(1)

    output_header = sys.argv[1]
    input_paths = sys.argv[2:]
    output_asm = os.path.splitext(output_header)[0] + ".asm"

    files = []
    seen = set()

    for path in input_paths:
        if not os.path.exists(path):
            continue
        if os.path.isfile(path):
            if path not in seen:
                seen.add(path)
                parent = os.path.basename(os.path.dirname(path))
                files.append((os.path.basename(path), path, parent))
        elif os.path.isdir(path):
            for root, dirs, fnames in os.walk(path):
                for entry in sorted(fnames):
                    if entry == ".gitkeep" or entry.startswith("."):
                        continue
                    full_path = os.path.join(root, entry)
                    if full_path not in seen and os.path.isfile(full_path):
                        sz = os.path.getsize(full_path)
                        # Keep kernel.bin lean (<6MB total). Large full game files use Option 1 (fetch) or Option 2 (disk/iso).
                        if sz > 4 * 1024 * 1024 and not os.environ.get("EMBED_ALL_LARGE_ASSETS"):
                            print(f"[embed_assets] Skipping large asset ({sz // (1024*1024)}MB) to keep kernel lightweight: {entry}")
                            continue
                        seen.add(full_path)
                        parent = os.path.basename(root)
                        files.append((entry, full_path, parent))

    h_lines = []
    h_lines.append("/* Auto-generated by tools/embed_user_assets.py - DO NOT EDIT */")
    h_lines.append("#ifndef USER_ASSETS_H")
    h_lines.append("#define USER_ASSETS_H\n")
    h_lines.append("#include <stdint.h>")
    h_lines.append("#include <stddef.h>\n")

    h_lines.append("typedef struct {")
    h_lines.append("    const char *path;")
    h_lines.append("    const uint8_t *data;")
    h_lines.append("    size_t size;")
    h_lines.append("} embedded_asset_t;\n")

    asm_lines = []
    asm_lines.append("; Auto-generated by tools/embed_user_assets.py - DO NOT EDIT")
    asm_lines.append("section .rodata\n")

    registration_entries = []

    for idx, (basename, full_path, parent) in enumerate(files):
        sym_name = f"user_asset_{idx}_" + basename.replace(".", "_").replace("-", "_")
        file_size = os.path.getsize(full_path)

        # In ASM
        asm_lines.append(f"global {sym_name}")
        asm_lines.append(f"{sym_name}:")
        asm_lines.append(f'    incbin "{full_path}"\n')

        # In Header
        h_lines.append(f"extern const uint8_t {sym_name}[];")

        # Mount points:
        # 1. Direct root mount: /<basename>
        # 2. Folder mount: /<parent>/<basename> (e.g. /DOOM/DOOM.WAD)
        # 3. Bin folder mount: /bin/<parent>/<basename>
        reg_paths = [
            f"/games/{parent}/{basename}",
            f"/{basename}",
        ]
        if basename.lower() != basename:
            reg_paths.append(f"/games/{parent}/{basename.lower()}")
            reg_paths.append(f"/{basename.lower()}")

        seen_rp = set()
        for rp in reg_paths:
            if rp not in seen_rp:
                seen_rp.add(rp)
                registration_entries.append((rp, sym_name, file_size))

    if not files:
        asm_lines.append("; No user assets present\n")

    h_lines.append("\nstatic const embedded_asset_t embedded_assets[] = {")
    for path, sym_name, size in registration_entries:
        h_lines.append(f"    {{ \"{path}\", {sym_name}, {size} }},")
    if not registration_entries:
        h_lines.append("    { 0, 0, 0 }")
    h_lines.append("};\n")

    h_lines.append(f"#define EMBEDDED_ASSETS_COUNT {len(registration_entries)}\n")
    h_lines.append("#endif /* USER_ASSETS_H */\n")

    with open(output_header, "w") as f:
        f.write("\n".join(h_lines))

    with open(output_asm, "w") as f:
        f.write("\n".join(asm_lines))

    print(f"[embed_user_assets] Generated {output_header} and {output_asm} ({len(files)} files, {len(registration_entries)} mounts).")

if __name__ == "__main__":
    main()
