#!/usr/bin/env python3
"""
Convert compiled standalone userland ELF binaries into C header arrays
for embedding into the ArchaOS RAM VFS.
"""

import sys
import os

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output_header.h> <elf1> [elf2 ...]")
        sys.exit(1)

    output_header = sys.argv[1]
    elf_files = sys.argv[2:]

    lines = []
    lines.append("/* Auto-generated by tools/embed_user_binaries.py - DO NOT EDIT */")
    lines.append("#ifndef USER_BINARIES_H")
    lines.append("#define USER_BINARIES_H\n")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>\n")

    for elf_path in elf_files:
        basename = os.path.basename(elf_path)
        var_name = "binary_" + basename.replace(".", "_")

        with open(elf_path, "rb") as f:
            data = f.read()

        lines.append(f"/* Embedded ELF: {basename} ({len(data)} bytes) */")
        lines.append(f"static const uint8_t {var_name}[] = {{")
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            byte_strs = [f"0x{b:02x}" for b in chunk]
            comma = "," if (i + 12 < len(data)) else ""
            lines.append(f"  {', '.join(byte_strs)}{comma}")
        lines.append("};\n")
        lines.append(f"static const size_t {var_name}_len = sizeof({var_name});\n")

    # Generate metadata table for automated registration
    lines.append("typedef struct {")
    lines.append("    const char *path;")
    lines.append("    const uint8_t *data;")
    lines.append("    size_t size;")
    lines.append("} embedded_binary_t;\n")

    lines.append("static const embedded_binary_t embedded_binaries[] = {")
    for elf_path in elf_files:
        basename = os.path.basename(elf_path)
        var_name = "binary_" + basename.replace(".", "_")
        lines.append(f"    {{ \"/bin/{basename}\", {var_name}, sizeof({var_name}) }},")
    lines.append("};\n")
    lines.append(f"#define EMBEDDED_BINARIES_COUNT {len(elf_files)}\n")

    lines.append("#endif /* USER_BINARIES_H */\n")

    with open(output_header, "w") as f:
        f.write("\n".join(lines))

    print(f"[embed_user_binaries] Generated {output_header} with {len(elf_files)} binaries.")

if __name__ == "__main__":
    main()
