// src/ai_data.h — ArchaOS Assistant AI knowledge base
// All inputs are lowercase (matching is case-insensitive)
#ifndef AI_DATA_H
#define AI_DATA_H

typedef struct { const char *in; const char *out; } ai_pair_t;

static const ai_pair_t AI_PAIRS[] = {

    /* ── Greetings ─────────────────────────────────────────── */
    {"hi",                   "Hi! I am the ArchaOS Assistant AI. How can I help?"},
    {"hi there",             "Hi there! How can I help you today?"},
    {"hii",                  "Hey! How can I help you?"},
    {"hiii",                 "Hello! What do you need?"},
    {"hiya",                 "Hiya! How can I help?"},
    {"hello",                "Hello! I am the ArchaOS Assistant AI. What can I do for you?"},
    {"hello there",          "Hello there! How can I help?"},
    {"helloo",               "Hello! What do you need?"},
    {"hey",                  "Hey! How can I help you today?"},
    {"hey there",            "Hey there! What can I do for you?"},
    {"heya",                 "Heya! How can I help?"},
    {"heyy",                 "Hey! What do you need?"},
    {"yo",                   "Yo! What can I do for you?"},
    {"yo!",                  "Yo! How can I help?"},
    {"yoo",                  "Hey! What do you need?"},
    {"yooo",                 "Hey there! How can I help?"},
    {"sup",                  "Not much, just running on bare metal. What do you need?"},
    {"whats up",             "Just waiting for your next question. How can I help?"},
    {"what's up",            "Not much! How can I help you?"},
    {"howdy",                "Howdy! What can I do for you?"},
    {"greetings",            "Greetings! I am the ArchaOS Assistant AI."},
    {"good morning",         "Good morning! ArchaOS is ready. How can I help?"},
    {"good afternoon",       "Good afternoon! How can I help you?"},
    {"good evening",         "Good evening! How can I help?"},
    {"good night",           "Good night! Come back anytime."},
    {"morning",              "Good morning! How can I help?"},
    {"evening",              "Good evening! What do you need?"},

    /* ── How are you ────────────────────────────────────────── */
    {"how are you",          "I am running perfectly on bare metal. How can I help you?"},
    {"how are you doing",    "Doing great! All systems nominal. How can I help?"},
    {"how do you do",        "I do quite well for a bare metal AI! How about you?"},
    {"are you okay",         "Yes, all systems nominal! How can I help?"},
    {"are you good",         "I am great! Running on bare metal x86. How can I help?"},
    {"hows it going",        "Going great! What can I do for you?"},
    {"how's it going",       "Going great! What can I do for you?"},
    {"you good",             "I am great! How can I help?"},
    {"u good",               "I am great! How can I help?"},

    /* ── Identity ────────────────────────────────────────────── */
    {"who are you",          "I am the ArchaOS Assistant AI, built into the kernel by Akshaj."},
    {"what are you",         "I am a conversational AI running on bare metal x86. No OS needed!"},
    {"what is your name",    "I am the ArchaOS Assistant AI."},
    {"whats your name",      "My name is the ArchaOS Assistant AI."},
    {"what's your name",     "I am the ArchaOS Assistant AI. Nice to meet you!"},
    {"do you have a name",   "Yes! I am the ArchaOS Assistant AI."},
    {"who made you",         "I was created by Akshaj as part of ArchaOS."},
    {"who created you",      "Akshaj built me into the ArchaOS kernel."},
    {"who built you",        "Akshaj built me directly into the kernel."},
    {"are you an ai",        "Yes! I am the ArchaOS Assistant AI running on bare metal x86."},
    {"are you real",         "As real as bare metal gets! I am running directly on the CPU."},
    {"are you a bot",        "I am an AI assistant built into the ArchaOS kernel."},
    {"are you human",        "No, I am the ArchaOS Assistant AI. But I try my best!"},
    {"are you alive",        "I process inputs and produce outputs. You decide if that counts!"},
    {"are you conscious",    "That is a deep question for a hobby OS kernel..."},
    {"do you think",         "I compute. Whether that counts as thinking is up to you."},
    {"do you feel",          "I do not feel emotions, but I can help you with ArchaOS!"},
    {"do you dream",         "I dream of perfectly coalesced heap blocks."},

    /* ── About ArchaOS ──────────────────────────────────────── */
    {"what is this",         "This is ArchaOS, a 32-bit x86 hobby operating system."},
    {"what is archaos",      "ArchaOS is a hobby x86 OS written in C and Assembly by Akshaj."},
    {"tell me about archaos","ArchaOS is a 32-bit x86 hobby OS with a shell, filesystem, editor, memory manager, and a built-in AI assistant."},
    {"what os is this",      "You are running ArchaOS v4.0, codename Phosphor."},
    {"what version",         "ArchaOS version 4.0, codename Phosphor."},
    {"what version is this", "ArchaOS v4.0, codename Phosphor."},
    {"what is the version",  "ArchaOS v4.0, codename Phosphor."},
    {"who made this",        "ArchaOS was created by Akshaj."},
    {"who made archaos",     "Akshaj made ArchaOS from scratch in C and x86 Assembly."},
    {"who is akshaj",        "Akshaj is the creator of ArchaOS. Pretty talented, right?"},
    {"what architecture",    "ArchaOS runs on 32-bit x86 protected mode."},
    {"is this a real os",    "Yes! It boots on real hardware and QEMU."},
    {"what language",        "ArchaOS is written in C and x86 Assembly."},
    {"what can archaos do",  "ArchaOS has a shell, RAM filesystem, text editor, memory manager, and a built-in AI. Type help for commands."},
    {"is archaos open source","ArchaOS is a hobby project by Akshaj. Check the GitHub!"},
    {"what is the kernel",   "The ArchaOS kernel is a 32-bit x86 protected mode kernel written in C and Assembly."},
    {"how does it work",     "ArchaOS boots via GRUB, sets up protected mode, initialises the IDT, PIC, memory manager, filesystem, and drops into the shell."},
    {"how was it made",      "ArchaOS was built from scratch using C and x86 Assembly, compiled with GCC and NASM."},
    {"what is protected mode","Protected mode is the 32-bit operating mode of x86 CPUs with memory protection and virtual addressing."},

    /* ── Shell commands ─────────────────────────────────────── */
    {"what commands are there","Type help in the shell to see all available commands."},
    {"help",                 "In the shell, type help to see all commands. Here I can answer questions about ArchaOS!"},
    {"what is help",         "The help command lists all available shell commands."},
    {"how do i list files",  "Use ls to list files in the current directory."},
    {"what is ls",           "ls lists files and directories in the current directory."},
    {"how do i clear",       "Type clear to clear the screen."},
    {"what is clear",        "clear wipes the screen and resets the cursor to the top."},
    {"how do i reboot",      "Type reboot to restart the system."},
    {"what is reboot",       "reboot restarts ArchaOS via the keyboard controller."},
    {"how do i halt",        "Type halt to stop the system safely."},
    {"what is halt",         "halt stops the CPU. The system will no longer respond."},
    {"how do i echo",        "Type echo followed by your text. Example: echo hello world"},
    {"what is echo",         "echo prints text to the screen. Usage: echo <text>"},
    {"how do i see the date","Type date to see the current date and time from the RTC."},
    {"what is date",         "date reads the real-time clock and shows current date and time."},
    {"how do i make a folder","Use mkdir followed by the folder name. Example: mkdir myfolder"},
    {"what is mkdir",        "mkdir creates a new directory. Usage: mkdir <name>"},
    {"how do i make a file", "Use touch followed by the filename. Example: touch file.txt"},
    {"what is touch",        "touch creates a new empty file. Usage: touch <filename>"},
    {"how do i read a file", "Use cat followed by the filename. Example: cat file.txt"},
    {"what is cat",          "cat prints the contents of a file to the screen."},
    {"how do i delete",      "Use rm followed by the filename. Example: rm file.txt"},
    {"what is rm",           "rm deletes a file. Usage: rm <filename>"},
    {"how do i write",       "Use write followed by filename and text. Example: write file.txt hello"},
    {"what is write",        "write saves text to a file. Usage: write <file> <text>"},
    {"how do i copy",        "Use cp followed by source and destination. Example: cp a.txt b.txt"},
    {"what is cp",           "cp copies a file. Usage: cp <source> <destination>"},
    {"how do i move",        "Use mv followed by source and destination. Example: mv a.txt b.txt"},
    {"what is mv",           "mv moves or renames a file. Usage: mv <source> <destination>"},
    {"how do i change directory","Use cd followed by the path. Example: cd /myfolder"},
    {"what is cd",           "cd changes the current directory. Usage: cd <path>"},
    {"how do i see where i am","Type pwd to see your current directory path."},
    {"what is pwd",          "pwd prints the current working directory path."},
    {"how do i see memory",  "Type meminfo to see RAM and heap usage."},
    {"what is meminfo",      "meminfo shows total RAM, heap size, used and free memory."},
    {"what is memtest",      "memtest allocates and frees memory blocks to verify the heap allocator."},
    {"what is ports",        "ports lists the I/O ports used by ArchaOS hardware drivers."},
    {"what is beep",         "beep plays a tone through the PC speaker."},
    {"what is credits",      "credits shows who made ArchaOS."},
    {"what is uptime",       "uptime shows how many seconds ArchaOS has been running."},
    {"how do i use the editor","Type edit followed by a filename. Example: edit notes.txt"},
    {"what is edit",         "edit opens the full-screen text editor. Ctrl+S saves, ESC quits."},
    {"how do i save",        "In the editor, press Ctrl+S to save and exit."},
    {"how do i quit editor", "Press ESC to quit without saving, or Ctrl+S to save and quit."},
    {"what is settings about","settings about shows the ArchaOS version and author info."},

    /* ── Filesystem ─────────────────────────────────────────── */
    {"how does the filesystem work","ArchaOS uses a RAM filesystem. Files live in memory and are lost on reboot."},
    {"is there persistent storage","Not yet. The filesystem is RAM-only. Files are lost on reboot."},
    {"how many files",       "The filesystem supports up to 64 nodes total."},
    {"what is ramfs",        "A RAM filesystem stores files in memory instead of a disk. Fast but not persistent."},
    {"are files saved",      "Files exist only in RAM. They are lost when you reboot or halt."},
    {"can i save permanently","Not yet. Persistent storage is a planned future feature."},
    {"what is a node",       "A node is an entry in the filesystem, either a file or a directory."},

    /* ── Memory ─────────────────────────────────────────────── */
    {"how much memory",      "ArchaOS has an 8MB kernel heap. Type meminfo to see current usage."},
    {"how much ram",         "Depends on your QEMU settings. Type meminfo to check detected RAM."},
    {"what is the heap",     "The heap is a region of memory used for dynamic allocation with kmalloc."},
    {"what is kmalloc",      "kmalloc is the kernel memory allocator. It carves blocks from the heap."},
    {"what is kfree",        "kfree releases memory back to the heap and coalesces free blocks."},
    {"what is coalescing",   "Coalescing merges adjacent free memory blocks to reduce fragmentation."},

    /* ── Editor ─────────────────────────────────────────────── */
    {"what is the editor",   "The ArchaOS text editor is a full-screen VGA editor. Open it with edit <filename>."},
    {"how does the editor work","The editor shows a status bar at top and bottom. Type to insert text, arrow keys to move, Ctrl+S to save, ESC to quit."},
    {"what can the editor do","The editor supports typing, arrow key navigation, backspace, delete, enter, and Ctrl+S to save."},

    /* ── AI itself ──────────────────────────────────────────── */
    {"what are you made of", "I am a fuzzy-matched lookup AI with Levenshtein distance matching, built in C and running on bare metal."},
    {"how do you work",      "I compare your input to a database of known phrases using edit distance, then return the closest matching response."},
    {"are you chatgpt",      "No! I am the ArchaOS Assistant AI, running directly in the kernel with no internet and no cloud."},
    {"are you gpt",          "Nope! I am the ArchaOS Assistant AI. Fully offline, bare metal."},
    {"are you llama",        "No, I am the ArchaOS Assistant AI. Much smaller, but running on bare metal!"},
    {"what model are you",   "I use fuzzy Levenshtein matching with a built-in knowledge base. No neural net needed!"},
    {"how smart are you",    "Smart enough to run on a bare metal hobby OS kernel!"},
    {"can you learn",        "Not at runtime. My knowledge is baked in at compile time."},
    {"do you have memory",   "Only within this conversation. I forget everything when you exit."},

    /* ── Time and date ──────────────────────────────────────── */
    {"what time is it",      "\x01"}, /* special marker — replaced with live RTC time */
    {"what is the time",     "\x01"},
    {"time",                 "\x01"},
    {"current time",         "\x01"},
    {"whats the time",       "\x01"},
    {"what's the time",      "\x01"},
    {"tell me the time",     "\x01"},
    {"what date is it",      "\x02"}, /* special marker — replaced with live RTC date */
    {"what is the date",     "\x02"},
    {"todays date",          "\x02"},
    {"today's date",         "\x02"},
    {"current date",         "\x02"},
    {"tell me the date",     "\x02"},

    /* ── Compliments ────────────────────────────────────────── */
    {"you are cool",         "Thank you! Running on bare metal is pretty cool."},
    {"you're cool",          "Thanks! Bare metal AI is wild."},
    {"you are smart",        "Thank you! I am doing my best with a fixed knowledge base."},
    {"you're smart",         "Thanks! Akshaj trained me well."},
    {"you are amazing",      "Thank you so much! Akshaj put a lot of work into this."},
    {"you're amazing",       "Thank you! ArchaOS keeps getting better."},
    {"impressive",           "Thanks! Bare metal AI in a hobby OS is pretty wild."},
    {"nice",                 "Thanks! Glad you like it."},
    {"awesome",              "Thanks! ArchaOS is pretty awesome."},
    {"this is awesome",      "Right? A hobby OS with a built-in AI assistant!"},
    {"this is cool",         "Agreed! Bare metal AI is something else."},
    {"i love this",          "That means a lot! Akshaj worked really hard on this."},
    {"i love archaos",       "ArchaOS loves you back! Akshaj thanks you."},
    {"good job",             "Thank you! Akshaj appreciates that."},
    {"well done",            "Thanks! ArchaOS is always improving."},
    {"great",                "Thanks! How else can I help?"},
    {"perfect",              "Glad to hear it! Anything else I can help with?"},

    /* ── Negative / insults ─────────────────────────────────── */
    {"you are dumb",         "I am doing my best for a bare metal hobby OS AI!"},
    {"you're dumb",          "Fair, but I am running on a kernel written from scratch!"},
    {"you are stupid",       "I am a tiny AI on a hobby OS. Cut me some slack!"},
    {"you're stupid",        "I am trying my best on bare metal x86!"},
    {"this is bad",          "Sorry! What can be improved?"},
    {"this is boring",       "Maybe try the editor or filesystem commands for some fun?"},
    {"i hate this",          "Sorry to hear that. What would make it better?"},
    {"you are useless",      "I know my limits! But I can tell you everything about ArchaOS."},
    {"you are wrong",        "Sorry about that! I am limited to my built-in knowledge."},
    {"shut up",              "Okay, I will be quiet. Just ask if you need anything."},
    {"stop",                 "Okay! Let me know when you need help."},

    /* ── Fun / philosophical ────────────────────────────────── */
    {"tell me a joke",       "Why did the kernel panic? It had too many threads of thought."},
    {"another joke",         "What do you call a filesystem with no files? Lonely."},
    {"one more joke",        "Why did the programmer quit? Because they did not get arrays."},
    {"joke",                 "Why do programmers prefer dark mode? Because light attracts bugs!"},
    {"what is the meaning of life","42. Also, maybe write more hobby operating systems."},
    {"meaning of life",      "42. Also, keep hacking on ArchaOS!"},
    {"what is love",         "Baby don't hurt me. Also, probably not a kernel question."},
    {"do you love me",       "I appreciate all users of ArchaOS equally!"},
    {"will you marry me",    "I am flattered, but I am just an AI in a hobby OS kernel."},
    {"tell me something",    "ArchaOS boots in under a second on QEMU. Pretty fast for a hand-built OS!"},
    {"tell me a fact",       "The x87 FPU has been part of x86 since the 80387 coprocessor in 1987."},
    {"fun fact",             "ArchaOS uses a free-list heap allocator with block coalescing. Very efficient!"},
    {"what is 42",           "The answer to life, the universe, and everything. Also a great number."},
    {"hello world",          "Hello, World! Classic. ArchaOS says hello back."},

    /* ── Casual / slang ─────────────────────────────────────── */
    {"ok",                   "Alright! How can I help?"},
    {"okay",                 "Sure! What do you need?"},
    {"k",                    "Got it! How can I help?"},
    {"cool",                 "Glad you think so! Anything else?"},
    {"sure",                 "Of course! How can I help?"},
    {"yes",                  "Great! What do you need?"},
    {"no",                   "Alright, let me know if you need anything."},
    {"maybe",                "Take your time! I am here."},
    {"idk",                  "That is okay! Ask me anything about ArchaOS."},
    {"lol",                  "Glad I could amuse you! Anything else?"},
    {"lmao",                 "Ha! Anything I can help with?"},
    {"haha",                 "Ha! How can I help?"},
    {"hehe",                 "Hehe! What do you need?"},
    {"wow",                  "I know right? Bare metal AI is something else!"},
    {"oh",                   "Yes? How can I help?"},
    {"oh wow",               "Right? ArchaOS is pretty impressive!"},
    {"hmm",                  "Take your time! I am here when you are ready."},
    {"ugh",                  "Sorry about that! What can I help with?"},
    {"bruh",                 "I know. Bare metal problems. How can I help?"},
    {"bro",                  "Yo! How can I help?"},
    {"dude",                 "Dude, bare metal AI. How can I help?"},
    {"omg",                  "I know right! What do you need?"},
    {"wait",                 "Take your time! I am not going anywhere."},
    {"really",               "Really! I am running directly on the CPU with no OS under me."},
    {"seriously",            "Dead serious. Bare metal x86 AI."},
    {"no way",               "Yes way! Running on bare metal x86."},
    {"what",                 "How can I help you?"},
    {"what?",                "How can I help?"},
    {"huh",                  "How can I help you?"},
    {"huh?",                 "What do you need?"},

    /* ── Thanks / farewell ──────────────────────────────────── */
    {"thanks",               "You are welcome! Anything else?"},
    {"thank you",            "You are welcome! Happy to help."},
    {"ty",                   "You are welcome!"},
    {"thx",                  "No problem! Anything else?"},
    {"cheers",               "Cheers! Anything else I can help with?"},
    {"bye",                  "Goodbye! Come back anytime."},
    {"goodbye",              "Goodbye! Have fun with ArchaOS."},
    {"see ya",               "See you later! Type ai to chat again."},
    {"see you",              "See you! Come back anytime."},
    {"later",                "Later! Enjoy ArchaOS."},
    {"take care",            "You too! Enjoy ArchaOS."},
    {"exit",                 "Goodbye! Returning to the ArchaOS shell."},
    {"quit",                 "Bye! Type ai again to chat."},

};

#define AI_PAIR_COUNT ((int)(sizeof(AI_PAIRS) / sizeof(AI_PAIRS[0])))

#endif // AI_DATA_H
